#!/bin/sh
#
# Wrapper script for winetricks compatability
#
# Copyright (C) 2018-2024 Dean M Greer
#
# This library is free software; you can redistribute it and/or
# modify it under the terms of the GNU Lesser General Public
# License as published by the Free Software Foundation; either
# version 2.1 of the License, or (at your option) any later version.
#
# This library is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public
# License along with this library; if not, write to the Free Software
# Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301, USA
#

# workaround SIP DYLD_stripping
# see https://support.apple.com/en-us/HT204899
export WINETRICKS_FALLBACK_LIBRARY_PATH="$(dirname "$0")/../../../Frameworks:$(dirname "$0")/../../../Frameworks/GStreamer.framework/Libraries"

export GST_PLUGIN_PATH="$(dirname "$0")/../../../Frameworks/GStreamer.framework/Libraries/gstreamer-1.0"
export WINESKINPATH="$(dirname "$0")/../../../SharedSupport/wine/bin"
export WINEPREFIX="${WINEPREFIX:-$(dirname "$0")/../../../SharedSupport/prefix}"

if [[ ${OSTYPE:6} -ge 23 && "$(/usr/bin/env arch -x86_64 /usr/sbin/sysctl -in sysctl.proc_translated)" = "1" && -n "${WINED3DMETAL}" ]]; then
    export D3DMETALPATH="$(dirname "$0")/../../../Frameworks/d3dmetal/wine"
    export WINETRICKS_FALLBACK_LIBRARY_PATH="$(dirname "$0")/../../../Frameworks/moltenvkcx:${WINETRICKS_FALLBACK_LIBRARY_PATH}"
    export WINEDLLOVERRIDES="*dxgi,*d3d10core,*d3d11,*d3d12=b"
fi

export DYLD_FALLBACK_LIBRARY_PATH="${WINETRICKS_FALLBACK_LIBRARY_PATH}"

# .Net 7 and later segfault under Rosetta2
# https://github.com/dotnet/runtime/issues/94909
export DOTNET="DOTNET_EnableWriteXorExecute=0"

# Pre macOS Catalina check for wine and use if found
if [[ ${OSTYPE:6} -lt 19 && -x "$(command -v "$WINESKINPATH"/wine)" ]]; then exec "$WINESKINPATH/wine" "${@}"; fi

# macOS Catalina or greater check for wine32on64 and use if found (CX19-CX21)
if [[ ${OSTYPE:6} -ge 19 && -x "$(command -v "$WINESKINPATH"/wine32on64)" ]]; then exec "$WINESKINPATH/wine32on64" "${@}"; fi

# Check for wine64 and use if found, fallback incase of wow64 or 64Bit only Engine
if [[ -x "$(command -v "$WINESKINPATH"/wine64)" ]]; then exec "$WINESKINPATH/wine64" "${@}"; fi

echo "Error: the wine loader was not found in $WINESKINPATH"
exit 1
